### ISSUE TITLE
Comment syntax and accessibility

### ISSUE THREAD

**Issue by kelseasy** [rust-lang-nursery/fmt-rfcs#120] opened 2018-03-22 04:50 UTC
Hi there!

In the wake of a discussion following accessibility, it was pointed out that the comment syntax for blind programmers has a far better user experience when using block comments (https://github.com/rust-lang/rfcs/pull/1373#issuecomment-205864317), but the style goes against that.

Given the purely stylistic nature of it, shouldn't accessibility be prioritised to offer a better experience to disabled people?

**Comment by solson** [comment] 2018-03-30 22:56
This was previously considered, including with the input of author of the comment you linked to, at https://github.com/rust-lang-nursery/fmt-rfcs/issues/17. I'm not sure that we need to rehash it again, so I'm closing this, but feel free to reopen (or reply on #17, I suppose) if you have a fresh take on it.

A quick summary of what I can recall about the thread:
* Line comments are default, in line with the preference of the vast majority of the community
* However, block comments are still available as an option
* It may be more accessible to change the default, but it's out of scope for the style team to pick defaults counter to the established norm and try to convince everyone to accept it.
* @camlorn [noted](https://github.com/rust-lang-nursery/fmt-rfcs/issues/17#issuecomment-265592007) in particular that while line comments are an irritation, they were not a barrier to being productive as a blind programmer.

**Closed by solson** 2018-03-30 22:56 UTC

**Comment by skade** [comment] 2018-04-16 09:32
I was recently discussing this with a blind community member from Dresden, who absolutely loves the "///" standard, as they are using a [refreshable braille display](https://en.wikipedia.org/wiki/Refreshable_braille_display). These are standard in Europe, but not so much in the US, where screenreading is preferred.

When using these displays, you are quickly going line-by-line, with tactile display. The "///" default is much better in this case then block comments, as you immediately get context.

So, a better way to interact with the problem is see which methods of accessibility we support better or worse.
