### ISSUE TITLE
Ordering of types of groups within a module

### ISSUE THREAD

**Issue by johnthagen** [rust-lang-nursery/fmt-rfcs#71] opened 2017-03-07 12:54 UTC
Is there any guidance about the general order of how things should be defined in a module? For example.

```rust
extern crate ...

use ...

// Declaring modules.
mod ...

// Rest of code: consts, structs, impl, functions, trait, etc
```

I'm unclear where `mod` declarations should go (before `use` or after `use`?). I can't find if this has been discussed before. I'm not sure it's something `rustfmt` would try to fix, but having a guideline could still be helpful. Relates to #24.

**Edit:** ~~Sometimes you need to declare a `mod` before you can import it:~~

**Comment by steveklabnik** [comment] 2017-03-07 14:44
Also related to (almost a dup of?) https://github.com/rust-lang-nursery/fmt-rfcs/issues/24

**Comment by johnthagen** [comment] 2017-03-07 16:19
Yeah, I almost commented on #24 but wasn't sure if it was on topic or not.

**Comment by solson** [comment] 2017-03-07 18:00
I think this deserves its own issue. It's more general than #24 in that it talks about every kind of item and the entire module.

I was chatting about this just the other day, and the order I typically follow is like this (let me know if I am forgetting something):

1. `extern crate`
2. `use`
3. `mod <name>`
4. mixed `const`/`static`
5. mixed `struct`/`enum`/`union`/`type`/`trait`
6. `impl`
7. `fn`
8. `mod test { ... }`

That said, I'm not sure rustfmt should strictly control this ordering. Some might find that too invasive or obstructive to their desired code organization. We could provide such an ordering as a guideline in the style guide.

But I would be okay with rustfmt forcing `extern crate`/`use`/`mod <name>` to be at the top and in the order decided by issues like #24.

> Sometimes you need to declare a mod before you can import it:

@johnthagen I'm fairly sure this is wrong (e.g. see [here](https://is.gd/L7LbZl)) and if the order ever mattered I would consider it a bug. Can you make a reproducible test case?

**Comment by solson** [comment] 2017-03-07 18:05
Additionally, within the `mixed struct/enum/union/type/trait` and `impl` sections, I try to follow the same relative ordering of types, like:

```rust
struct A { ... }
enum B { ... }
impl A { ... }
impl B { ... }
impl Foo for B {... }
```

I picked this style so all my data definition are in one place, as opposed to the following mixed types/impls style:

```rust
struct A { ... }
impl A { ... }
enum B { ... }
impl B { ... }
impl Foo for B {... }
```

**Comment by jplatte** [comment] 2017-03-07 18:18
There are two things that are usually above everything you've listed so far: file-scoped `//!` doc comments (module / crate documentation) and file-scoped `#![...]` attributes. I think I'd put them in that order - doc comments first, then attributes.

**Comment by joshtriplett** [comment] 2017-03-07 18:27
@solson I agree that rustfmt shouldn't reorder those, except perhaps for `extern crate`, `use`, and `mod`.

I don't agree that const and static always belong at the top; sometimes they belong next to a block of related functions that use them.

Regarding struct, enum, and impl, I personally prefer the mixed style: `impl A` belongs immediately after `struct A`.  And `impl Foo for B` belongs either right after `impl B` or right after `trait Foo`, whichever makes more sense to associate it with.  (Depends on if you think of it as "defining a trait and impls for various types" or "defining a type and impls for various traits", both of which can make sense.  And, of course, if either the trait or the type appears in some other crate, you only have one of those options available.)

I do agree that `mod tests {` belongs at the end.  More generally, I'd suggest that any inline-defined module (e.g. `mod foo { ... }` rather than `mod foo;`) belongs either at the beginning right after all the `mod foo;` declarations *or* at the end before `mod tests {`.  Whether the module belongs at the beginning or at the end can differ on a case-by-case basis; in general, I'd say that a small helper module that exists for intra-crate usage, or a module defined with a `cfg(target)` and gets consumed or re-exported by a portable exported API belongs at the top, while a module that exists to export APIs consumed outside the crate belongs at the bottom.  But while we might provide guidelines on that, I don't think we should mandate it.

**Comment by solson** [comment] 2017-03-07 18:36
> I don't agree that const and static always belong at the top; sometimes they belong next to a block of related functions that use them.

I wasn't so sure about my placement for these. I guess the spot I put them is where I dump them if I have no better idea.

> But that can vary a bit if you have a set of highly interlinked structs; in that case, it might make sense to declare the interlinked structs together, then write the impls. So in general, I don't think we should specify the order between struct/union, enum, impl, and impl-for.

Agreed. I was considering defining a set of structs/enums together which contain each other in some kind of tree structure (which comes up a lot for me), but it's not a universal rule.

**Comment by solson** [comment] 2017-03-07 18:37
I just remembered something else: `macro_rules` and, I suppose, the upcoming `macro` system.

I tend to write `macro_rules` all at the top of the file, just after `use`s, since `macro_rules` are actually order-dependent. With an order-independent `macro` I would probably place them closer to top-level `fn`s.

**Comment by johnthagen** [comment] 2017-03-08 02:20
>I'm fairly sure this is wrong (e.g. see here) and if the order ever mattered I would consider it a bug. Can you make a reproducible test case?

You are absolutely correct, I was wrong about this.

**Comment by nrc** [comment] 2017-03-14 22:20
I think we could recommend:

1. extern crate
2. use
3. mod
4. everything else

Both in modules and functions. Beyond that I feel like there are too many special cases, or trade-offs to make a strong recommendation.

I also think that by default Rustfmt should not make this change, but it would be nice if we could opt in to it.

**Comment by solson** [comment] 2017-03-14 22:27
I'm in favor of rustfmt enforcing the order @nrc mentioned by default (leaving everything in 4 in its original order).

Hiding a module-scope `extern crate`, `use`, or `mod <name>` among the items later in the file seems like a pretty misleading style given the strong convention of placing them at the top. I've never seen anyone do it intentionally.

**Comment by nrc** [comment] 2017-03-14 22:32
@solson mod declarations sometimes have to come after macro declarations in order for the macro to be visible.

Macro uses in general might appear anywhere within the 3 groups, I think.

I've occasionally put `use` near an `impl` which is the client, though I'm not sure that is really good style.

**Comment by solson** [comment] 2017-03-14 22:36
Ah, yeah, `macro_rules`'s order-sensitivity ruins a lot of things. :)

Maybe we can automatically move `extern crate` and `use` to the top, but only give a strong recommendation for `mod`.

> I've occasionally put use near an impl which is the client, though I'm not sure that is really good style.

I do consider this bad style. I like when the answer to the question "where does this name come from" is answered in a single predictable place for all names.

**Comment by joshtriplett** [comment] 2017-03-14 23:50
There's a *strong* convention of putting `mod tests {` at the end of a module; I don't want to break that.

**Comment by solson** [comment] 2017-03-14 23:53
Although it's name varies (`mod test {`, `mod tests {`, possibly other things). Can we even make a reasonable rule for rustfmt here?

We should definitely mention `mod tests {`-at-the-end as a guideline for humans, at least.

**Comment by nrc** [comment] 2017-03-14 23:56
I think actually the name is not too important - inline mods belong with everything else, only placeholder mods should be at the top (I'd put `mod test;` at the top, rather than bottom).

**Comment by SergioBenitez** [comment] 2017-03-22 22:13
I _strongly_ prefer for the ordering of imports to be:

  1. `extern`
  2. `mod`
  3. `use`

This ordering follows the module hierarchy, from "most" global to local. An `extern` is importing code from outside of the crate, a `mod` is importing code from outside of the current module, and a `use` bringing code already inside the current module into the local namespace.

**Comment by solson** [comment] 2017-03-22 23:19
In my mind, the *global → local* ordering is that which people suggested earlier:

1. `extern crate` - the widest scope, pulling crate-external code into the crate
2. `use` - the second widest scope, pulling possibly module-external items into the module
3. `mod` - definitions of submodules nested within the current module

**Comment by SergioBenitez** [comment] 2017-03-22 23:39
@solson A non-inline `mod` is _always_ pulling code from outside of the current module, while a `use` brings identifiers reachable _from the current namespace into the current namespace_. Another way to look at this is that `mod` _does not_ depend on the local namespace (instead only on the file hierarchy) while `use` does. As a result, `use` is confined to more local reasoning.

I suspect that some of the preference for the `extern` -> `use` -> `mod` ordering is due to the fact that older versions of `rustc` required this ordering due to limitations. I recall that many users found this confusing, often asking "how can I be `use`ing something that I haven't imported via `mod`?" The problem was so prevalent that the Rust book mentioned this peculiarity exactly, referring to it as a _limitation_ of the compiler.

**Comment by solson** [comment] 2017-03-23 00:04
> A non-inline mod is always pulling code from outside of the current module

I disagree with this phrasing. It's defining a submodule inside the current module and that code is nested inside the current module even though it's in a different *file*. I suspect our disagreement stems from the fact that I view `mod` items as definitions but your wording suggests you view them as imports.

> I suspect that some of the preference for the extern -> use -> mod ordering is due to the fact that older versions of rustc required this ordering due to limitations

I prefer this ordering because to me it's the most natural expression of "external imports first, local definitions after".

**Comment by SergioBenitez** [comment] 2017-03-23 00:32
> I suspect our disagreement stems from the fact that I view mod items as definitions but your wording suggests you view them as imports.

Perhaps this is part of it. But if we consider why users had an issue with this ordering, I believe it's because it feels like, and indeed is, a "use before definition". I strive to have definitions appear before their use in my source code. This is why `fn main()` is always at the bottom of the file, and why I try to declare functions before their use. This ordering feels intuitive and normal: I want to know what something is before it's used.

**Comment by solson** [comment] 2017-03-23 00:58
> I believe it's because it feels like, and indeed is, a "use before definition". I strive to have definitions appear before their use in my source code. This is why fn main() is always at the bottom of the file, and why I try to define functions before their use. This ordering feels intuitive and normal.

Ah... I don't think in this way. I was quite happy that Rust did not enforce definition-use ordering. I like to put the most "high-level" things first, like `struct Foo(A, B)` and put the smaller things like `A` and `B` later. Likewise I would put the most high-level function first and the subroutines it calls to handle the details below. The high-level things act like a "table of contents" and give context for the details to come. I may have an easier time understanding a function if I already know where and why it's called.

> There is empirical evidence that the ordering extern -> use -> mod strikes a dissonant chord with users, but I have never observed the same issue with the ordering I propose.

Well, I am myself an example of seeing `extern` → `mod` → `use` as *imports* → *definitions* → *imports*, which seems like the same issue.

----

All that said, I feel like I'm *mostly* disagreeing with the supporting points you've brought up, and not your actual proposal. :)

I wouldn't terribly mind either order, but I'd like to see more feedback from the community at large. I feel like there are not many distinct voices on this thread so far.

**Comment by johnthagen** [comment] 2017-03-23 01:31
I'm +1 towards `use` first because in all language I've ever used I always pull in code (import) at the first. I agree with @solson's view of `mod` as a declaration. Yes it's actually defined in another file, but the `mod` statement declares whether it's `pub` or not and thus is at least defining *something* about it.

**Comment by ebkalderon** [comment] 2017-03-30 16:21
Expanding on @johnthagen's example, below is my preferred list including `pub`:

1. `pub extern crate` (only in lib.rs)
2. `extern crate` (only in lib.rs or main.rs)
3. `pub use`
4. `use`
5. `pub mod`
6. `mod`

**Comment by steveklabnik** [comment] 2017-04-03 22:08
I always `mod` before `use` for the same reasons as @SergioBenitez

**Comment by nrc** [comment] 2017-04-03 22:09
So, the question from @ebkalderon is (I think) whether `pub` items should be separated out from non-pub ones? Also note that `pub` is no longer a monolithic thing and we have `pub(restricted)` now too.

I'm against recommending that `extern crate` should only be used in lib.rs/main.rs - I think it is useful sometimes to import a crate more locally.

**Comment by nrc** [comment] 2017-04-03 22:25
We discussed this issue at the style team meeting. The two outstanding questions are:
* the ordering of `use` vs `mod`. We decided that we would like to know what the consensus is currently. The best way to do this would be a scan of crates.io. @joshtriplett may do so if he can leverage Crater locally to do this. If anyone else is interested in helping/doing this, please give us a shout.
* whether `pub` items should be separated - we decided no because there is no consensus on the ordering, and it makes sense in some cases but not others. Although the motivation for making `pub` stuff easier to find is good, this is undermined by having `pub` items of different kinds in different places and is better addressed by tooling.

**Comment by joshtriplett** [comment] 2017-04-04 03:47
I downloaded and analyzed all the sources on crates.io (just cloned the index and used curl to download all the .crate files).

I'm still doing the full analysis, but as a preliminary observation, I noticed the following pattern that suggests we probably *can't* reorder mod and use relative to each other:

```rust
#[cfg(target_os = "linux")]
mod linux;
#[cfg(target_os = "linux")]
use linux as os;

#[cfg(target_os = "macos")]
mod macos;
#[cfg(target_os = "macos")]
use macos as os;

#[cfg(windows)]
mod windows;
#[cfg(windows)]
use windows as os;
```

That seems completely sensible, and we should not do anything to break that pattern.

**Comment by joshtriplett** [comment] 2017-04-04 04:03
OK, I just finished analyzing all 8487 crates from crates.io.

A total of 2096 crates use both `use` and `mod`.  Of those:

768 crates use `mod` before `use` and never the reverse.
814 crates use `use` before `mod` and never the reverse.
514 crates do *both*.

That seems to indicate a complete lack of any standard convention.  Between that and the specific cases I quoted above, I'd consider this conclusive evidence that we should not attempt to reorder `use` and `mod` statements.

**Comment by joshtriplett** [comment] 2017-04-04 04:10
If you'd like to do some further analysis, [results.txt](https://github.com/rust-lang-nursery/fmt-rfcs/files/892023/results.txt) contains a summary of every .rs file on crates.io that contains `^use `, `^pub use `, or `^mod .*;` .  The file contains filenames (which may include spaces) followed by a column containing a series of `m`, `p`, and `u` characters, for `mod`, `pub use`, and `use`, respectively.

(Note that while that file contains one entry per Rust source file, I would recommend doing the analysis by crate rather than by file, to avoid overcounting the conventions of crates with more source files.)

**Comment by nrc** [comment] 2017-04-04 04:16
Awesome, thanks @joshtriplett ! Did you notice any instances where `extern crate` was deliberately interleaved with `use`s or `mod`s?

**Comment by nrc** [comment] 2017-04-04 04:19
Given this data and our discussion I'd like to propose the following:

* we recommend and enforce that `extern crate`s come at the start of a file
* we recommend and enforce that `mod`s and `use`s come before other items
* we recommend, but do not enforce, `use`s come before `mod`s and that `mod`s and `use`s are kept separate unless there is semantic reason to do so.

Rationale for the recommendation is that this is what the (slim) majority of crates and the Rust repo does.

**Comment by johnthagen** [comment] 2017-04-04 12:14
> we recommend, but do not enforce, `use`s come before `mod`s and that `mod`s and `use`s are kept separate unless there is semantic reason to do so.

I like this. Part of the reasons for a lack of standard convention could very well be because one has never been offered (the whole point of this project), so this seems like a very sensible compromise. Hopefully over time we then see a gradual conformity for a majority of projects.

**Comment by joshtriplett** [comment] 2017-04-04 17:26
@nrc I just did a check for `extern crate`.

7450 crates contained a file with both an `extern crate` line and one of the other types of items. Of those, 492 contained an `extern crate` line after one of the other types of items, and 6958 did not.

Of those, I see two common patterns:

- Putting `use` lines for `std` before `extern crate`, and all other `use` lines after.
- Pairing `extern crate x` with the corresponding `use x::...`.

Personally, I would propose the following:

- We recommend and enforce that `extern crate`, `mod` (out-of-line only), and `use` (including `pub use`) come before all other items.
- We recommend but do not enforce putting `extern crate` first, then `use`, then `mod`.
- We encourage withoutboats to complete the work that makes `extern crate x;` redundant in favor of `use x;`, and once that becomes widely available in stable Rust, we recommend and enforce using `use` instead of `extern crate`, and we recommend and enforce combining adjacent `use` statements for the same module.

**Comment by nrc** [comment] 2017-04-04 20:44
Thanks for collecting the data!

>  (out-of-line only)

Yes, this is a good clarification

> We recommend but do not enforce putting extern crate first, then use, then mod.

I think the difference here is you think rustfmt should not move out `extern crate`s to the top of the file. ISTM that the majority of crates do this and it is reasonable to do. The small number of exceptions seem like something that can be handled by `rustfmt_skip` or by turning off an option (and to clarify I think all this re-ordering should be behind options, I'm just discussing defaults here) if the authors feel strongly about it.

> We support @withoutboats' proposal 

I don't think we should have an opinion on a language issue.

**Comment by joshtriplett** [comment] 2017-04-04 22:12
@nrc Are you OK with pulling all the `extern crate` lines to the top of the file when the author interleaved them right before the corresponding `use` line for that crate's items?  I don't *object* to doing so, but I wonder.

And the only reason I commented on the language proposal is that eliminating `extern crate` in favor of `use` rather nicely avoids the problem, and I *do* think we should have an opinion on the style of the resulting language after such a change.

**Comment by nrc** [comment] 2017-04-04 22:44
> Are you OK with pulling all the extern crate lines to the top of the file when the author interleaved them right before the corresponding use line for that crate's items? I don't object to doing so, but I wonder.

Yes. This doesn't feel any worse than (e.g.) using block formatting where the author used visual formatting. And if they strongly object they can turn off the option.

> And the only reason I commented on the language proposal is that eliminating extern crate in favor of use rather nicely avoids the problem, and I do think we should have an opinion on the style of the resulting language after such a change.

Although you are right that it would avoid the problem, it seems like a rather large change for a rather minor problem. If that happens for other reasons, then of course we should have an opinion on the style in the resulting language, but I don't think our motivation is strong enough to try and influence the decision there.

**Comment by ebkalderon** [comment] 2017-04-15 05:25
@nrc If I may ask, did you arrive at an ultimate consensus for how to handle the ordering of `pub {use,mod}`?

**Comment by nrc** [comment] 2017-05-01 00:21
@ebkalderon I don't think we did exactly. I've been away for a few weeks and I'll try and get to this soon.

**Comment by nrc** [comment] 2017-05-09 03:46
Summary of recommendations (assume mods = out-of-line mods for all of this):

* extern crates, mods, and uses come before other items (enforced, optional)
* extern crates come before mods and uses (enforced, optional)
* uses come before mods (optionally enforced, off by default)
* uses, mods, and extern crates are alphabetically ordered (enforced only if the category is separated, and optional)
* we make no recommendation about ordering of pub vs non-pub items

**Closed** 2018-02-05 04:03 UTC
Labels: has-PR

**Comment by mathstuf** [comment] 2018-02-05 14:41
@nrc I think that instead of `extern crate statements must be first in a file.`, it should be `extern crate statements must be first in a scope.`.

**Comment by matklad** [comment] 2018-07-03 22:56
Curious: are all the people sure that out-of-line mod declarations should be sorted alphabetically? 

I think I have a pretty strong argument for preserving the order of `mods`  that the programmer specified. 

A good logical ordering (for example. from low-level to high-level) of `mod`s is a **huge** help for reading the code for the first time: you can see that `foo`, `bar` and `baz` are small helpers and `spam` and `eggs` are complicated beasts where the interesting stuff happens. 

To me, mod declarations seems much closer to function definitions than to imports, because their ordering has the potential to expose the high-level structure of the code.

This probably doesn't matter if you working with a particular code-base a lot, because you are most likely using navigation by type or file names. 

However, if you are just diving in into the base, figuring out which 20% of code is actually interesting can be very challenging, and here I think manually ordered mod declarations can help a lot?

**Comment by topecongiro** [comment] 2018-07-04 03:38
FWIW you can just put the important modules in a separate group to not get reordered with others.

For example, given the following code,

```rust
mod foo;
mod bar;
mod baz;

mod spams;
mod eggs;
```

it should be formatted like:

```rust
mod bar;
mod baz;
mod foo;

mod eggs;
mod spams;
```

**Comment by nrc** [comment] 2018-07-06 00:43
> A good logical ordering (for example. from low-level to high-level) of mods is a huge help for reading the code for the first time

Our consensus about this sort of thing was that ordering is a weak and implicit way to supply information and we shouldn't encourage it (for one thing, the reader has to expect you to be ordering/grouping modules to recognise that there is actually information there). We thought that letting the user group modules using whitespace but not maintain order otherwise was a good compromise.
