### ISSUE TITLE
How to format #[macro_use]

### ISSUE THREAD

**Issue by johnthagen** [rust-lang-nursery/fmt-rfcs#44] opened 2016-12-14 13:47 UTC
A [question](https://github.com/intellij-rust/intellij-rust/issues/834) came up on the `intellij-rust` issue tracker about whether the default format for a `#[macro_use]` should be:

```rust
#[macro_use(foo, bar)]
extern crate baz;

#[macro_use]
mod baa;
```

Or
```rust
#[macro_use(foo, bar)] extern crate baz;

#[macro_use] mod baa;
```

The examples I saw in the [book](https://doc.rust-lang.org/beta/book/macros.html#scoping-and-macro-importexport) seemed to indicate the first. Was wondering if this had been discussed or decided.

**Comment by regexident** [comment] 2016-12-14 14:34
This already has an issue: https://github.com/rust-lang-nursery/fmt-rfcs/issues/36

**Comment by steveklabnik** [comment] 2016-12-14 17:10
Yes, this is a duplicate of that issue. Thanks!

**Closed by steveklabnik** 2016-12-14 17:10 UTC

**Comment by johnthagen** [comment] 2016-12-14 17:59
Thanks for the reference @regexident!
